### ISSUE TITLE
确认段落与段落间需要留两个空行吗

### ISSUE THREAD

**Issue by ShuoXiTheInari** [SparkPlugWS/MGEchm#2]
一个br就是一个空行

<p>与其外表一样，每个魅魔的性格也不一致，唯一不变的是她们的淫荡本性与对性欲的渴求。</p>
  <br><br>
  <p>魅魔所拥有的强大魔力，通常都用以勾引人类。</p>
  <p>当她们找到人类男性之后，就会通过自己美丽的容姿、魅惑法</p>
这个是空了两行了

**Comment by ShuoXiTheInari** [comment]
大概是01魅魔多打了一个<br>，不过有必要完全复刻段落吗……

**Comment by SparkPlugWS** [comment]
如果你直接制作html文档的话，不必理会我在“提取文字”那个部分的格式要求，模仿范例去安排p和br就好

> 不过有必要完全复刻段落吗……

这是我希望的效果，或许并不一定必要，你可以先按照自己舒服的样子来，如果将来我觉得有必要我会再找回来改的
